name: magic_ai_assessment
description: "A Magic AI project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  go_router: ^16.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  freezed_annotation: ^3.1.0
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  sqlite3_flutter_libs: ^0.5.39
  get_it: ^8.2.0
  collection: ^1.19.1

  intl: ^0.20.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  bloc_test: ^10.0.0
  mocktail: ^1.0.3
  build_runner: ^2.7.0
  freezed: ^3.2.0
  drift_dev: ^2.28.1
  flutter_lints: ^6.0.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/